-- MySQL Script generated by MySQL Workbench
-- Wed 31 Jan 2018 04:01:04 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema book
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema book
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `book` DEFAULT CHARACTER SET utf8 ;
USE `book` ;

-- -----------------------------------------------------
-- Table `book`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book`.`genre` ;

CREATE TABLE IF NOT EXISTS `book`.`genre` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book`.`book` ;

CREATE TABLE IF NOT EXISTS `book`.`book` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `author` VARCHAR(64) NULL,
  `release_date` DATE NULL,
  `genre_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_book_genre_idx` (`genre_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `book`.`genre`
-- -----------------------------------------------------
START TRANSACTION;
USE `book`;
INSERT INTO `book`.`genre` (`id`, `name`) VALUES (1, 'Drame');
INSERT INTO `book`.`genre` (`id`, `name`) VALUES (2, 'Poésie');
INSERT INTO `book`.`genre` (`id`, `name`) VALUES (3, 'Thriller');
INSERT INTO `book`.`genre` (`id`, `name`) VALUES (4, 'Théâtre');

COMMIT;


-- -----------------------------------------------------
-- Data for table `book`.`book`
-- -----------------------------------------------------
START TRANSACTION;
USE `book`;
INSERT INTO `book`.`book` (`id`, `name`, `author`, `release_date`, `genre_id`) VALUES (1, 'Autant en emporte le vent', 'Mitchell Margaret', '1936-05-04', 1);
INSERT INTO `book`.`book` (`id`, `name`, `author`, `release_date`, `genre_id`) VALUES (2, 'Poèmes saturniens', 'Verlaine Paul', '1866-02-01', 2);
INSERT INTO `book`.`book` (`id`, `name`, `author`, `release_date`, `genre_id`) VALUES (3, 'Par accident', 'Cohen Harlan', '2019-04-02', 3);
INSERT INTO `book`.`book` (`id`, `name`, `author`, `release_date`, `genre_id`) VALUES (4, 'Hamlet', 'Shakespeare William', '1609-09-10', 4);

COMMIT;
